### PR TITLE
Album art fetching from HTTP server

### PR DESCRIPTION
**Pull request by bartkl**
Hi!

I love the miniplayer, but my album art isn't present in the files.

Instead, since I'm using the Android clients [MPDroid](https://play.google.com/store/apps/details?id=com.namelessdev.mpdroid&hl=en_US&gl=US) and [MAFA](https://play.google.com/store/apps/details?id=software.indi.android.mpd&hl=en_US&gl=US) a lot, I've followed the instructions provided by the [MPDroid wiki](https://github.com/abarisain/dmix/wiki/Album-Art-on-your-LAN) to set up an HTTP server that serves my album art for me. Both of these players support this exact implementation, and of course other users/developers can use it as well.

So, I forked your repository and altered and expanded on the code to make it support album art fetching from such an HTTP server.

If it interests you, I hope you will merge these changes to upstream. Of course I'm more than willing to change the code/approach where desired as well :).

If you do feel this is a worthy addition, here's a summary of what I did:
- Since there are now more settings regarding album art fetching, I felt a config section `art` was in order. I've moved `music_directory` and `image_method` there, and added the new `http_base_url` and `http_cover_filenames` options.
- There is now a central `Player.getAlbumArt` method, which will, based on the config, fetch art from the HTTP server, or from the files. Each of these routes have their own private method in the `Player` class.
- I made the default album art drawing logic a separate function `Player.drawDefaultAlbumArt`, especially now that it's called from several places.
- I've updated the example config and README. It might be a bit minimal though.

Two things I feel uncertain about is:
- Whatever the image is, it is always saved to the `/tmp` directory with a PNG file extension. Of course this should be an issue just as much with retrieving album art from files, and that seems to work fine. Also, I've tested with a JPG file from my HTTP server, and it seems to work just fine there too.
- I bumped minor version, but since I moved some existing config keys around, this release would not be compatible with current configs, so therefore it might be better to make this a major version upgrade (2.0.0 for instance).

Let me hear what you think. No worries if you reject the feature altogether, I can maintain a fork if necessary :).

Thanks,
Bart

### CODE REVIEW

**Comment by GuardKenzie** [comment]
This looks really good, thank you so much for your contribution! I love the changes you made, they really do clean up the code quite a bit.

> Whatever the image is, it is always saved to the /tmp directory with a PNG file extension. Of course this should be an issue just as much with retrieving album art from files, and that seems to work fine. Also, I've tested with a JPG file from my HTTP server, and it seems to work just fine there too.

The `.png` file extension is really just a hint for ffmpeg so it knows I want the album art from the song file. The equivalent command in the terminal would be `ffmpeg -i song.mp3 /tmp/aartminip.png`. When you fetch the cover art files from your server, you are writing, for example, `jpeg`  data (along with all it's identifiers) to a file that just happens to have the file extension `.png`. Since the libraries we are using to display the album art don't care about file names, just the actual file data, this does not cause issues.

**Review by GuardKenzie — CHANGES_REQUESTED** [review]
> I bumped minor version, but since I moved some existing config keys around, this release would not be compatible with current configs, so therefore it might be better to make this a major version upgrade (2.0.0 for instance).

I don't think this change warrants a major version upgrade so here is my suggestion: 

A better solution imo would be to check if `music_directory` is present under the `player` config section and if it is, print a deprecation notice like:
```python
print(("The config option 'music_directory' under the 'player' section is deprecated "
       "and will be removed in the future. Use the config option 'music_directory' "
       "under the 'art' section instead.")
    )
input("(Press enter to continue)...")
```
and do the same for the `image_method` config option.

A few notes on this:

- Config options under the `art` section should have precedence over ones under the `player` section
- The old config options should still be supported and should work just the same, except they print the deprecation notice.
- If there is more than one notice, they should both be printed and the user should only need to press enter once for the player to start

**Comment by bartkl** [comment]
Sorry for the late response! I didn't get any notification from GitHub for some reason, and I was very busy also.

Thanks for the kind words. I'll take a closer look on your feedback and hopefully make the desired changes soon :).



Bart

**Comment by bartkl** [comment]
I added some code to handle the config compatibility issue. I think it ticks all the boxes you desire.

I'm working on my work laptop currently so I cannot test it yet, but maybe you can glance at these few lines of code and at least give me a sign if this is indeed in the direction you'd like.

**Comment by GuardKenzie** [comment]
This is really good! Thank you so much for taking interest in the project!

**Pull request merged**
