### PR TITLE
Change config location to xdg directory

### PR DESCRIPTION
**Pull request by tye-singwa**
Hi! This is proposed change to #25

### CODE REVIEW

**Review by GuardKenzie — CHANGES_REQUESTED** [review]
Hi! Thanks for your pull request and interest in this project! This is a very good point, I should have considered this when I first set this up.

Since the `pyxdg` package performs such a simple task, I don't really like adding it as a dependency. It would be very easy to implement this functionality directly with `os.environ` (and some checks to make sure the directory exists etc.).

It would be amazing if you were to consider doing that but if you don't want to, I can of course do it myself in the future.

**Comment by tye-singwa** [comment]
Thanks for quick review!
Agree that additional dependency is little bit too much for such simple task, I've removed it from PR.

**Review by GuardKenzie — CHANGES_REQUESTED** [review]
Hi! Sorry for the late reply. This looks really good but a check to see if the `XDG_CONFIG_HOME` directory actually exists would be good. After that I'll merge it.

**Comment by GuardKenzie** [comment]
This has been implemented with 2d8d5ebfde01063757be35c0fe59ed4b6037a0ce

**Pull request closed without merging**
